version = 1

[[analyzers]]
name = "go"
enabled = true

  [analyzers.meta]
  import_path = "github.com/teetlab/pkg"

[[analyzers]]
name = "test-coverage"
enabled = true

[[analyzers]]
name = "terraform"
enabled = true
